### ISSUE TITLE
Compiling error on vs2017/19

### ISSUE THREAD

**Issue by Speedvicio** [petschau/WinFellow#31]
There are any problems in the source compilation, relative to version info "WORDS" comma problem, and with specific path to windows kits version relative to missing fxc.exe.

For fxc.exe I have solved by changing the path of windows kits, that could be changed into a more generic path instead refer to a specific version installed:
C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64
into
C:\Program Files (x86)\Windows Kits\10\bin\x64

for version problems i have solved removing this references into WinFellow.vcxproj

<ClInclude Include="GUI_versioninfo.h" />
<ResourceCompile Include="GUI_versioninfo.rc" />

**Comment by carfesh** [comment]
Thanks for bringing this to our attention; I tried this in a recent commit (91e592263055686734f1b89aab5a0835199b00cf), but had to revert that because on my installation, the shader compiler fxc.exe is not contained in that generic path. So if this is persisting, I'd try installing the SDK version that is referenced in the project files.

About compilation, the version specific stuff (you probably had messages like versioninfo.h missing,m etc.) is generated via script; for that to work, a few things need to be in the search path. We use a PowerShell script (CompileReleaseBuild.ps1) to perform unattended builds from a clean checked-out copy. For that to work, the installation should be set up according to the "HOWTO Development environment setup.md". Only parts of that are needed if you want to compile from Visual Studio, though. Debug builds are also more tolerant, compilation of a release build requires the working copy to be clean.

**Comment by carfesh** [comment]
I've updated the GitWCRev script to allow compilation of WinFellow from source code downloaded directly from GitHub (f45a9d70451b5476517dc1fcccf6866657178530). It will have a different versioning and naming scheme, but for archival and future testing it may be helpful to have this functionality. Hopefully this fixes the compilation issues you encountered.

**Comment by Speedvicio** [comment]
Another error:

Gravità	Codice	Descrizione	Progetto	File	Riga	Stato eliminazione
Errore	MSB3073	uscita dal comando "PowerShell.exe ..\Scripts\GitWCRev.ps1 -InputFileName ..\INCLUDE\versioninfo-wcrev.h -OutputFileName ..\INCLUDE\versioninfo.h
PowerShell.exe ..\Scripts\GitWCRev.ps1 -InputFileName ..\MSVC\GUI_versioninfo-wcrev.rc -OutputFileName ..\MSVC\GUI_versioninfo.rc
:VCEnd" con codice 1.	WinFellow	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	128

**Comment by carfesh** [comment]
Are you compiling a debug build, or a release build? What sources are you compiling from?

There is a kind of workflow in place there, which may be your issue. During development we will usually work with **debug** builds. They are better to debug and have additional logging in place. Debug builds compile fine even if you have made changes to your working copy of the Git repository, so you can test whatever change you want to do to your heart's content before committing it, with very few restrictions. 

For a **release** build, the script will abort the build if it detects local changes in your working copy.

This is intended behavior, to ensure that release builds are always created from clean sources. It's also not an issue, as whatever you want to test, you can fork a copy of WinFellow, commit your changes to your fork and compile a release build from your fork. If you then later raise a pull request with the changes you propose, that would be awesome 🥇

May I ask what you are trying to work on?

**Comment by Speedvicio** [comment]
I'm compiling the debug version, the source is cloned by master GitHub repo by visual studio community 2017 and 2019.
With previous WinFellow commit and with that change I have maked into WinFellow.vcxproj removing reference to GUI_versioninfo, i can compile the source.
Anyway is not a problem, I can wait for a stable release, when it will be ready.
