### ISSUE TITLE
[BUG] dxgi.dll on XP

### ISSUE THREAD

**Issue by TheElf01** [petschau/WinFellow#70]
White the 32bits executable in XP dont ask for dxgi.dll the 64bits yes, and dont start in XP x64

 - OS: XPp x64

I check the executable and the function CreateDXGIFactory.dxgi.dll is present in the 64bits while not in the 32bits

No idea if is a bug or the 64bits version is not XP compatible

thanks

**Comment by petschau** [comment]
Hi, thanks for reporting the issue. The dxgi.dll is related to Direct 3D 11 that we only load if the platform supports it, or if not supported, we just fall back to using directdraw. The 64-bit version had it incorrectly linked as a dependency though. It was fixed some time ago in the repo by changes related to issue #68 , so it'll be fixed in the next version.
